# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu120/xset/val_data_bone.npy
  label_path: ./data/ntu120/xset/val_label.pkl
  debug: False

# model
model: model.agcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'


# test
phase: test
device: [3]
test_batch_size: 64
weights: ./runs/ntu120_cv_agcn_bone-47-83952.pt

work_dir: ./work_dir/ntu120/xview/agcn_test_bone
model_saved_name: ./runs/ntu120_cv_agcn_test_bone
save_score: True